package com.zyc.model;

import java.util.Date;

public class Ip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.ipid
     *
     * @mbg.generated
     */
    private Integer ipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.x
     *
     * @mbg.generated
     */
    private String x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.y
     *
     * @mbg.generated
     */
    private String y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IP.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IP
     *
     * @mbg.generated
     */
    public Ip(Integer ipid, String ip, String location, String x, String y, Date date) {
        this.ipid = ipid;
        this.ip = ip;
        this.location = location;
        this.x = x;
        this.y = y;
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IP
     *
     * @mbg.generated
     */
    public Ip() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.ipid
     *
     * @return the value of IP.ipid
     *
     * @mbg.generated
     */
    public Integer getIpid() {
        return ipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.ipid
     *
     * @param ipid the value for IP.ipid
     *
     * @mbg.generated
     */
    public void setIpid(Integer ipid) {
        this.ipid = ipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.ip
     *
     * @return the value of IP.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.ip
     *
     * @param ip the value for IP.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.location
     *
     * @return the value of IP.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.location
     *
     * @param location the value for IP.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.x
     *
     * @return the value of IP.x
     *
     * @mbg.generated
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.x
     *
     * @param x the value for IP.x
     *
     * @mbg.generated
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.y
     *
     * @return the value of IP.y
     *
     * @mbg.generated
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.y
     *
     * @param y the value for IP.y
     *
     * @mbg.generated
     */
    public void setY(String y) {
        this.y = y == null ? null : y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IP.date
     *
     * @return the value of IP.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IP.date
     *
     * @param date the value for IP.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}