package com.zyc.model;

public class Usertorole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserToRole.utrid
     *
     * @mbg.generated
     */
    private Integer utrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserToRole.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserToRole.roleid
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    public Usertorole(Integer utrid, Integer userid, Integer roleid) {
        this.utrid = utrid;
        this.userid = userid;
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    public Usertorole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserToRole.utrid
     *
     * @return the value of UserToRole.utrid
     *
     * @mbg.generated
     */
    public Integer getUtrid() {
        return utrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserToRole.utrid
     *
     * @param utrid the value for UserToRole.utrid
     *
     * @mbg.generated
     */
    public void setUtrid(Integer utrid) {
        this.utrid = utrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserToRole.userid
     *
     * @return the value of UserToRole.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserToRole.userid
     *
     * @param userid the value for UserToRole.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserToRole.roleid
     *
     * @return the value of UserToRole.roleid
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserToRole.roleid
     *
     * @param roleid the value for UserToRole.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}