package com.zyc.model;

import java.util.Date;

public class Wenzhang {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangid
     *
     * @mbg.generated
     */
    private Integer wenzhangid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangleixing
     *
     * @mbg.generated
     */
    private String wenzhangleixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangbiaoti
     *
     * @mbg.generated
     */
    private String wenzhangbiaoti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangneirong
     *
     * @mbg.generated
     */
    private String wenzhangneirong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangchunwenben
     *
     * @mbg.generated
     */
    private String wenzhangchunwenben;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangriqi
     *
     * @mbg.generated
     */
    private Date wenzhangriqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wenzhang.wenzhangauthor
     *
     * @mbg.generated
     */
    private Integer wenzhangauthor;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public Wenzhang(Integer wenzhangid, String wenzhangleixing, String wenzhangbiaoti, String wenzhangneirong, String wenzhangchunwenben, Date wenzhangriqi, Integer wenzhangauthor) {
        this.wenzhangid = wenzhangid;
        this.wenzhangleixing = wenzhangleixing;
        this.wenzhangbiaoti = wenzhangbiaoti;
        this.wenzhangneirong = wenzhangneirong;
        this.wenzhangchunwenben = wenzhangchunwenben;
        this.wenzhangriqi = wenzhangriqi;
        this.wenzhangauthor = wenzhangauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public Wenzhang() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangid
     *
     * @return the value of wenzhang.wenzhangid
     *
     * @mbg.generated
     */
    public Integer getWenzhangid() {
        return wenzhangid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangid
     *
     * @param wenzhangid the value for wenzhang.wenzhangid
     *
     * @mbg.generated
     */
    public void setWenzhangid(Integer wenzhangid) {
        this.wenzhangid = wenzhangid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangleixing
     *
     * @return the value of wenzhang.wenzhangleixing
     *
     * @mbg.generated
     */
    public String getWenzhangleixing() {
        return wenzhangleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangleixing
     *
     * @param wenzhangleixing the value for wenzhang.wenzhangleixing
     *
     * @mbg.generated
     */
    public void setWenzhangleixing(String wenzhangleixing) {
        this.wenzhangleixing = wenzhangleixing == null ? null : wenzhangleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangbiaoti
     *
     * @return the value of wenzhang.wenzhangbiaoti
     *
     * @mbg.generated
     */
    public String getWenzhangbiaoti() {
        return wenzhangbiaoti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangbiaoti
     *
     * @param wenzhangbiaoti the value for wenzhang.wenzhangbiaoti
     *
     * @mbg.generated
     */
    public void setWenzhangbiaoti(String wenzhangbiaoti) {
        this.wenzhangbiaoti = wenzhangbiaoti == null ? null : wenzhangbiaoti.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangneirong
     *
     * @return the value of wenzhang.wenzhangneirong
     *
     * @mbg.generated
     */
    public String getWenzhangneirong() {
        return wenzhangneirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangneirong
     *
     * @param wenzhangneirong the value for wenzhang.wenzhangneirong
     *
     * @mbg.generated
     */
    public void setWenzhangneirong(String wenzhangneirong) {
        this.wenzhangneirong = wenzhangneirong == null ? null : wenzhangneirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangchunwenben
     *
     * @return the value of wenzhang.wenzhangchunwenben
     *
     * @mbg.generated
     */
    public String getWenzhangchunwenben() {
        return wenzhangchunwenben;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangchunwenben
     *
     * @param wenzhangchunwenben the value for wenzhang.wenzhangchunwenben
     *
     * @mbg.generated
     */
    public void setWenzhangchunwenben(String wenzhangchunwenben) {
        this.wenzhangchunwenben = wenzhangchunwenben == null ? null : wenzhangchunwenben.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangriqi
     *
     * @return the value of wenzhang.wenzhangriqi
     *
     * @mbg.generated
     */
    public Date getWenzhangriqi() {
        return wenzhangriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangriqi
     *
     * @param wenzhangriqi the value for wenzhang.wenzhangriqi
     *
     * @mbg.generated
     */
    public void setWenzhangriqi(Date wenzhangriqi) {
        this.wenzhangriqi = wenzhangriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wenzhang.wenzhangauthor
     *
     * @return the value of wenzhang.wenzhangauthor
     *
     * @mbg.generated
     */
    public Integer getWenzhangauthor() {
        return wenzhangauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wenzhang.wenzhangauthor
     *
     * @param wenzhangauthor the value for wenzhang.wenzhangauthor
     *
     * @mbg.generated
     */
    public void setWenzhangauthor(Integer wenzhangauthor) {
        this.wenzhangauthor = wenzhangauthor;
    }
}