package com.zyc.mapper;

import com.zyc.model.Usertorole;
import com.zyc.model.UsertoroleExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface UsertoroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    long countByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    int deleteByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    @Delete({
        "delete from UserToRole",
        "where utrid = #{utrid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer utrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    @Insert({
        "insert into UserToRole (utrid, userid, ",
        "roleid)",
        "values (#{utrid,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{roleid,jdbcType=INTEGER})"
    })
    int insert(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    int insertSelective(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    List<Usertorole> selectByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "utrid, userid, roleid",
        "from UserToRole",
        "where utrid = #{utrid,jdbcType=INTEGER}"
    })
    @ResultMap("com.zyc.mapper.UsertoroleMapper.BaseResultMap")
    Usertorole selectByPrimaryKey(Integer utrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usertorole record, @Param("example") UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usertorole record, @Param("example") UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserToRole
     *
     * @mbg.generated
     */
    @Update({
        "update UserToRole",
        "set userid = #{userid,jdbcType=INTEGER},",
          "roleid = #{roleid,jdbcType=INTEGER}",
        "where utrid = #{utrid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Usertorole record);
}