package com.zyc.model;

import java.util.Date;

public class Logrecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.Logid
     *
     * @mbg.generated
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.Userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.IP
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.TableName
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.Action
     *
     * @mbg.generated
     */
    private Integer action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.LogRecord
     *
     * @mbg.generated
     */
    private String logrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LogRecord.RecordDate
     *
     * @mbg.generated
     */
    private Date recorddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    public Logrecord(Integer logid, Integer userid, String username, String ip, String tablename, Integer action, String logrecord, Date recorddate) {
        this.logid = logid;
        this.userid = userid;
        this.username = username;
        this.ip = ip;
        this.tablename = tablename;
        this.action = action;
        this.logrecord = logrecord;
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    public Logrecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.Logid
     *
     * @return the value of LogRecord.Logid
     *
     * @mbg.generated
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.Logid
     *
     * @param logid the value for LogRecord.Logid
     *
     * @mbg.generated
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.Userid
     *
     * @return the value of LogRecord.Userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.Userid
     *
     * @param userid the value for LogRecord.Userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.UserName
     *
     * @return the value of LogRecord.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.UserName
     *
     * @param username the value for LogRecord.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.IP
     *
     * @return the value of LogRecord.IP
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.IP
     *
     * @param ip the value for LogRecord.IP
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.TableName
     *
     * @return the value of LogRecord.TableName
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.TableName
     *
     * @param tablename the value for LogRecord.TableName
     *
     * @mbg.generated
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.Action
     *
     * @return the value of LogRecord.Action
     *
     * @mbg.generated
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.Action
     *
     * @param action the value for LogRecord.Action
     *
     * @mbg.generated
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.LogRecord
     *
     * @return the value of LogRecord.LogRecord
     *
     * @mbg.generated
     */
    public String getLogrecord() {
        return logrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.LogRecord
     *
     * @param logrecord the value for LogRecord.LogRecord
     *
     * @mbg.generated
     */
    public void setLogrecord(String logrecord) {
        this.logrecord = logrecord == null ? null : logrecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LogRecord.RecordDate
     *
     * @return the value of LogRecord.RecordDate
     *
     * @mbg.generated
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LogRecord.RecordDate
     *
     * @param recorddate the value for LogRecord.RecordDate
     *
     * @mbg.generated
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }
}