package com.zyc.model;

public class Power {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.powerid
     *
     * @mbg.generated
     */
    private Integer powerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.powername
     *
     * @mbg.generated
     */
    private String powername;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    public Power(Integer powerid, String powername) {
        this.powerid = powerid;
        this.powername = powername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    public Power() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.powerid
     *
     * @return the value of power.powerid
     *
     * @mbg.generated
     */
    public Integer getPowerid() {
        return powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.powerid
     *
     * @param powerid the value for power.powerid
     *
     * @mbg.generated
     */
    public void setPowerid(Integer powerid) {
        this.powerid = powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.powername
     *
     * @return the value of power.powername
     *
     * @mbg.generated
     */
    public String getPowername() {
        return powername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.powername
     *
     * @param powername the value for power.powername
     *
     * @mbg.generated
     */
    public void setPowername(String powername) {
        this.powername = powername == null ? null : powername.trim();
    }
}