package com.zyc.model;

public class Roletopower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleToPower.rtpid
     *
     * @mbg.generated
     */
    private Integer rtpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleToPower.roleid
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleToPower.powerid
     *
     * @mbg.generated
     */
    private Integer powerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    public Roletopower(Integer rtpid, Integer roleid, Integer powerid) {
        this.rtpid = rtpid;
        this.roleid = roleid;
        this.powerid = powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    public Roletopower() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleToPower.rtpid
     *
     * @return the value of RoleToPower.rtpid
     *
     * @mbg.generated
     */
    public Integer getRtpid() {
        return rtpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleToPower.rtpid
     *
     * @param rtpid the value for RoleToPower.rtpid
     *
     * @mbg.generated
     */
    public void setRtpid(Integer rtpid) {
        this.rtpid = rtpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleToPower.roleid
     *
     * @return the value of RoleToPower.roleid
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleToPower.roleid
     *
     * @param roleid the value for RoleToPower.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleToPower.powerid
     *
     * @return the value of RoleToPower.powerid
     *
     * @mbg.generated
     */
    public Integer getPowerid() {
        return powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleToPower.powerid
     *
     * @param powerid the value for RoleToPower.powerid
     *
     * @mbg.generated
     */
    public void setPowerid(Integer powerid) {
        this.powerid = powerid;
    }
}