package com.zyc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WenzhangExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public WenzhangExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWenzhangidIsNull() {
            addCriterion("wenzhangid is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangidIsNotNull() {
            addCriterion("wenzhangid is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangidEqualTo(Integer value) {
            addCriterion("wenzhangid =", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidNotEqualTo(Integer value) {
            addCriterion("wenzhangid <>", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidGreaterThan(Integer value) {
            addCriterion("wenzhangid >", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wenzhangid >=", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidLessThan(Integer value) {
            addCriterion("wenzhangid <", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidLessThanOrEqualTo(Integer value) {
            addCriterion("wenzhangid <=", value, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidIn(List<Integer> values) {
            addCriterion("wenzhangid in", values, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidNotIn(List<Integer> values) {
            addCriterion("wenzhangid not in", values, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidBetween(Integer value1, Integer value2) {
            addCriterion("wenzhangid between", value1, value2, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangidNotBetween(Integer value1, Integer value2) {
            addCriterion("wenzhangid not between", value1, value2, "wenzhangid");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingIsNull() {
            addCriterion("wenzhangleixing is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingIsNotNull() {
            addCriterion("wenzhangleixing is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingEqualTo(String value) {
            addCriterion("wenzhangleixing =", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingNotEqualTo(String value) {
            addCriterion("wenzhangleixing <>", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingGreaterThan(String value) {
            addCriterion("wenzhangleixing >", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingGreaterThanOrEqualTo(String value) {
            addCriterion("wenzhangleixing >=", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingLessThan(String value) {
            addCriterion("wenzhangleixing <", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingLessThanOrEqualTo(String value) {
            addCriterion("wenzhangleixing <=", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingLike(String value) {
            addCriterion("wenzhangleixing like", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingNotLike(String value) {
            addCriterion("wenzhangleixing not like", value, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingIn(List<String> values) {
            addCriterion("wenzhangleixing in", values, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingNotIn(List<String> values) {
            addCriterion("wenzhangleixing not in", values, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingBetween(String value1, String value2) {
            addCriterion("wenzhangleixing between", value1, value2, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangleixingNotBetween(String value1, String value2) {
            addCriterion("wenzhangleixing not between", value1, value2, "wenzhangleixing");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiIsNull() {
            addCriterion("wenzhangbiaoti is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiIsNotNull() {
            addCriterion("wenzhangbiaoti is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiEqualTo(String value) {
            addCriterion("wenzhangbiaoti =", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiNotEqualTo(String value) {
            addCriterion("wenzhangbiaoti <>", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiGreaterThan(String value) {
            addCriterion("wenzhangbiaoti >", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiGreaterThanOrEqualTo(String value) {
            addCriterion("wenzhangbiaoti >=", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiLessThan(String value) {
            addCriterion("wenzhangbiaoti <", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiLessThanOrEqualTo(String value) {
            addCriterion("wenzhangbiaoti <=", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiLike(String value) {
            addCriterion("wenzhangbiaoti like", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiNotLike(String value) {
            addCriterion("wenzhangbiaoti not like", value, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiIn(List<String> values) {
            addCriterion("wenzhangbiaoti in", values, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiNotIn(List<String> values) {
            addCriterion("wenzhangbiaoti not in", values, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiBetween(String value1, String value2) {
            addCriterion("wenzhangbiaoti between", value1, value2, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangbiaotiNotBetween(String value1, String value2) {
            addCriterion("wenzhangbiaoti not between", value1, value2, "wenzhangbiaoti");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongIsNull() {
            addCriterion("wenzhangneirong is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongIsNotNull() {
            addCriterion("wenzhangneirong is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongEqualTo(String value) {
            addCriterion("wenzhangneirong =", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongNotEqualTo(String value) {
            addCriterion("wenzhangneirong <>", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongGreaterThan(String value) {
            addCriterion("wenzhangneirong >", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongGreaterThanOrEqualTo(String value) {
            addCriterion("wenzhangneirong >=", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongLessThan(String value) {
            addCriterion("wenzhangneirong <", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongLessThanOrEqualTo(String value) {
            addCriterion("wenzhangneirong <=", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongLike(String value) {
            addCriterion("wenzhangneirong like", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongNotLike(String value) {
            addCriterion("wenzhangneirong not like", value, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongIn(List<String> values) {
            addCriterion("wenzhangneirong in", values, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongNotIn(List<String> values) {
            addCriterion("wenzhangneirong not in", values, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongBetween(String value1, String value2) {
            addCriterion("wenzhangneirong between", value1, value2, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangneirongNotBetween(String value1, String value2) {
            addCriterion("wenzhangneirong not between", value1, value2, "wenzhangneirong");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenIsNull() {
            addCriterion("wenzhangchunwenben is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenIsNotNull() {
            addCriterion("wenzhangchunwenben is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenEqualTo(String value) {
            addCriterion("wenzhangchunwenben =", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenNotEqualTo(String value) {
            addCriterion("wenzhangchunwenben <>", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenGreaterThan(String value) {
            addCriterion("wenzhangchunwenben >", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenGreaterThanOrEqualTo(String value) {
            addCriterion("wenzhangchunwenben >=", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenLessThan(String value) {
            addCriterion("wenzhangchunwenben <", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenLessThanOrEqualTo(String value) {
            addCriterion("wenzhangchunwenben <=", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenLike(String value) {
            addCriterion("wenzhangchunwenben like", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenNotLike(String value) {
            addCriterion("wenzhangchunwenben not like", value, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenIn(List<String> values) {
            addCriterion("wenzhangchunwenben in", values, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenNotIn(List<String> values) {
            addCriterion("wenzhangchunwenben not in", values, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenBetween(String value1, String value2) {
            addCriterion("wenzhangchunwenben between", value1, value2, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangchunwenbenNotBetween(String value1, String value2) {
            addCriterion("wenzhangchunwenben not between", value1, value2, "wenzhangchunwenben");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiIsNull() {
            addCriterion("wenzhangriqi is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiIsNotNull() {
            addCriterion("wenzhangriqi is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiEqualTo(Date value) {
            addCriterion("wenzhangriqi =", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiNotEqualTo(Date value) {
            addCriterion("wenzhangriqi <>", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiGreaterThan(Date value) {
            addCriterion("wenzhangriqi >", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiGreaterThanOrEqualTo(Date value) {
            addCriterion("wenzhangriqi >=", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiLessThan(Date value) {
            addCriterion("wenzhangriqi <", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiLessThanOrEqualTo(Date value) {
            addCriterion("wenzhangriqi <=", value, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiIn(List<Date> values) {
            addCriterion("wenzhangriqi in", values, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiNotIn(List<Date> values) {
            addCriterion("wenzhangriqi not in", values, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiBetween(Date value1, Date value2) {
            addCriterion("wenzhangriqi between", value1, value2, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangriqiNotBetween(Date value1, Date value2) {
            addCriterion("wenzhangriqi not between", value1, value2, "wenzhangriqi");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorIsNull() {
            addCriterion("wenzhangauthor is null");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorIsNotNull() {
            addCriterion("wenzhangauthor is not null");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorEqualTo(Integer value) {
            addCriterion("wenzhangauthor =", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorNotEqualTo(Integer value) {
            addCriterion("wenzhangauthor <>", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorGreaterThan(Integer value) {
            addCriterion("wenzhangauthor >", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorGreaterThanOrEqualTo(Integer value) {
            addCriterion("wenzhangauthor >=", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorLessThan(Integer value) {
            addCriterion("wenzhangauthor <", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorLessThanOrEqualTo(Integer value) {
            addCriterion("wenzhangauthor <=", value, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorIn(List<Integer> values) {
            addCriterion("wenzhangauthor in", values, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorNotIn(List<Integer> values) {
            addCriterion("wenzhangauthor not in", values, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorBetween(Integer value1, Integer value2) {
            addCriterion("wenzhangauthor between", value1, value2, "wenzhangauthor");
            return (Criteria) this;
        }

        public Criteria andWenzhangauthorNotBetween(Integer value1, Integer value2) {
            addCriterion("wenzhangauthor not between", value1, value2, "wenzhangauthor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wenzhang
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wenzhang
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}