package com.zyc.mapper;

import com.zyc.model.Logrecord;
import com.zyc.model.LogrecordExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface LogrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    long countByExample(LogrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    int deleteByExample(LogrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    @Delete({
        "delete from LogRecord",
        "where Logid = #{logid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    @Insert({
        "insert into LogRecord (Logid, Userid, ",
        "UserName, IP, TableName, ",
        "Action, LogRecord, ",
        "RecordDate)",
        "values (#{logid,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{username,jdbcType=VARCHAR}, #{ip,jdbcType=VARCHAR}, #{tablename,jdbcType=VARCHAR}, ",
        "#{action,jdbcType=INTEGER}, #{logrecord,jdbcType=VARCHAR}, ",
        "#{recorddate,jdbcType=TIMESTAMP})"
    })
    int insert(Logrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    int insertSelective(Logrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    List<Logrecord> selectByExample(LogrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "Logid, Userid, UserName, IP, TableName, Action, LogRecord, RecordDate",
        "from LogRecord",
        "where Logid = #{logid,jdbcType=INTEGER}"
    })
    @ResultMap("com.zyc.mapper.LogrecordMapper.BaseResultMap")
    Logrecord selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Logrecord record, @Param("example") LogrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Logrecord record, @Param("example") LogrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Logrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LogRecord
     *
     * @mbg.generated
     */
    @Update({
        "update LogRecord",
        "set Userid = #{userid,jdbcType=INTEGER},",
          "UserName = #{username,jdbcType=VARCHAR},",
          "IP = #{ip,jdbcType=VARCHAR},",
          "TableName = #{tablename,jdbcType=VARCHAR},",
          "Action = #{action,jdbcType=INTEGER},",
          "LogRecord = #{logrecord,jdbcType=VARCHAR},",
          "RecordDate = #{recorddate,jdbcType=TIMESTAMP}",
        "where Logid = #{logid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Logrecord record);
}