package com.zyc.mapper;

import com.zyc.model.Power;
import com.zyc.model.PowerExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.List;
public interface PowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    long countByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int deleteByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    @Delete({
        "delete from power",
        "where powerid = #{powerid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer powerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    @Insert({
        "insert into power (powerid, powername)",
        "values (#{powerid,jdbcType=INTEGER}, #{powername,jdbcType=VARCHAR})"
    })
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    List<Power> selectByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "powerid, powername",
        "from power",
        "where powerid = #{powerid,jdbcType=INTEGER}"
    })
    @ResultMap("com.zyc.mapper.PowerMapper.BaseResultMap")
    Power selectByPrimaryKey(Integer powerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    @Update({
        "update power",
        "set powername = #{powername,jdbcType=VARCHAR}",
        "where powerid = #{powerid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Power record);
}