package com.zyc.mapper;

import com.zyc.model.Roletopower;
import com.zyc.model.RoletopowerExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface RoletopowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    long countByExample(RoletopowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    int deleteByExample(RoletopowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    @Delete({
        "delete from RoleToPower",
        "where rtpid = #{rtpid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer rtpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    @Insert({
        "insert into RoleToPower (rtpid, roleid, ",
        "powerid)",
        "values (#{rtpid,jdbcType=INTEGER}, #{roleid,jdbcType=INTEGER}, ",
        "#{powerid,jdbcType=INTEGER})"
    })
    int insert(Roletopower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    int insertSelective(Roletopower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    List<Roletopower> selectByExample(RoletopowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "rtpid, roleid, powerid",
        "from RoleToPower",
        "where rtpid = #{rtpid,jdbcType=INTEGER}"
    })
    @ResultMap("com.zyc.mapper.RoletopowerMapper.BaseResultMap")
    Roletopower selectByPrimaryKey(Integer rtpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Roletopower record, @Param("example") RoletopowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Roletopower record, @Param("example") RoletopowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Roletopower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleToPower
     *
     * @mbg.generated
     */
    @Update({
        "update RoleToPower",
        "set roleid = #{roleid,jdbcType=INTEGER},",
          "powerid = #{powerid,jdbcType=INTEGER}",
        "where rtpid = #{rtpid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Roletopower record);
}